// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurJtNu7gIPmevfxJy2L03Vcu6dKyY4BY',
    appId: '1:433622438408:web:6952afdefcd9f8942237bd',
    messagingSenderId: '433622438408',
    projectId: 'kixar-5d7d5',
    authDomain: 'kixar-5d7d5.firebaseapp.com',
    storageBucket: 'kixar-5d7d5.firebasestorage.app',
    measurementId: 'G-N8XNEEXHJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe643KVjLq4xgU6I4nmZGn0ilN81_dnjU',
    appId: '1:433622438408:android:5b94de0787f60b922237bd',
    messagingSenderId: '433622438408',
    projectId: 'kixar-5d7d5',
    storageBucket: 'kixar-5d7d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cU8ec8ZREv2qScStKmjmpVzTLqbwb7A',
    appId: '1:433622438408:ios:bb30222269479ca72237bd',
    messagingSenderId: '433622438408',
    projectId: 'kixar-5d7d5',
    storageBucket: 'kixar-5d7d5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cU8ec8ZREv2qScStKmjmpVzTLqbwb7A',
    appId: '1:433622438408:ios:bb30222269479ca72237bd',
    messagingSenderId: '433622438408',
    projectId: 'kixar-5d7d5',
    storageBucket: 'kixar-5d7d5.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBurJtNu7gIPmevfxJy2L03Vcu6dKyY4BY',
    appId: '1:433622438408:web:a0a73bf2d75770fc2237bd',
    messagingSenderId: '433622438408',
    projectId: 'kixar-5d7d5',
    authDomain: 'kixar-5d7d5.firebaseapp.com',
    storageBucket: 'kixar-5d7d5.firebasestorage.app',
    measurementId: 'G-WY1MV37NYH',
  );
}